# Generated by Django 4.1.5 on 2023-01-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_remove_carteira_associacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='foto',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
