# Generated by Django 4.1.5 on 2023-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_carteira_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
