# Generated by Django 4.1.5 on 2023-01-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_carteira_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
    ]
