# Generated by Django 4.1.5 on 2023-02-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_carteira_cpf_alter_carteira_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='associacao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
